### ISSUE TITLE
USER/NICK

### ISSUE THREAD

**Issue by GQDeltex** [hennneh/ft_irc#15]
Parse User info from commands and store in userstore

**Comment by belgishboy** [comment]
@belgishboy check that user is _raspberry is true before can use USER and NICK
impliment errors for user and nick 
set _pi to true after Nick

**Comment by GQDeltex** [comment]
NICK can only begin with a letter `[a-z]|[A-Z]`. User can be any nonwhite character. See instructions at [RFC 1459 Section 2.3.1](https://datatracker.ietf.org/doc/html/rfc1459#section-2.3.1)
