### ISSUE TITLE
Find Client IP to create "unique" username

### ISSUE THREAD

**Issue by GQDeltex** [hennneh/ft_irc#17]
Somehow find out the IP of the connecting client

**Comment by GQDeltex** [comment]
https://stackoverflow.com/questions/25341862/how-to-find-clients-ip-address-using-tcp-socket-programming-in-c

**Comment by GQDeltex** [comment]
Add the ip as 'unique' identifier in the map while the connection is not yet verified (Current identifier `"unique"`)

**Comment by c8p2d01** [comment]
also, what was the purpose of this issue? when i looked into it the functions to find and store the clients ip were already implemented in the client class, i just changed the messages to actually include and print it. does this resolve the issue?

**Comment by GQDeltex** [comment]
In the IRC class in the run function we accept new connections which are currently stored with the key "unique" in the map. Use the IP address string there, otherwise no 2 clients can be in the connecting phase at the same time
