### ISSUE TITLE
channel modes

### ISSUE THREAD

**Issue by hennneh** [hennneh/ft_irc#25]
`<channel> {[+|-]|o|p|s|i|t|n|b|v} [<limit>] [<user>] [<ban mask>]`

**Comment by belgishboy** [comment]
@GQDeltex 
':Angel MODE Angel +i ' 
do we need to handle the fact the command is second ?
https://datatracker.ietf.org/doc/html/rfc1459#section-4.2.3

**Comment by belgishboy** [comment]
are we not doing ?:
m - moderated channel;
l - set the user limit to channel;
k - set a channel key (password).

**Comment by belgishboy** [comment]
What is the difference/ use of the [+|-] at the beginning?

**Comment by GQDeltex** [comment]
Add/Remove the mode/privilege.-------- Ursprüngliche Nachricht --------Von: Vincent Heymans ***@***.***>Datum: Sa., 30. Juli 2022, 17:10An: hennneh/ft_irc ***@***.***>Cc: GQDeltex ***@***.***>, Mention ***@***.***>Betreff: Re: [hennneh/ft_irc] channel modes (Issue #25)
What is the difference/ use of the [+|-] at the beginning?

**Comment by GQDeltex** [comment]
Command is still `MODE` just also look at the prefix. +/- is for adding/removing the mode/flag/privilege
