### ISSUE TITLE
JOIN

### ISSUE THREAD

**Issue by hennneh** [hennneh/ft_irc#47]
need join to be able to test our code

**Comment by hennneh** [comment]
while joining channels, there is an error called ERR_TOOMANYCHANNELS so is there a limit of channels we can join at once?

**Comment by belgishboy** [comment]
> while joining channels, there is an error called ERR_TOOMANYCHANNELS so is there a limit of channels we can join at once?

https://datatracker.ietf.org/doc/html/rfc1459#section-8.13
