### ISSUE TITLE
SERVER

### ISSUE THREAD

**Issue by belgishboy** [hennneh/ft_irc#59]
/connection
Command: SERVER
Parameters: < servername > < hopcount > < info >
https://datatracker.ietf.org/doc/html/rfc1459#section-4.1.4

Errors:
ERR_ALREADYREGISTRED

**Comment by hennneh** [comment]
do we actually need this? server-server connections aren't being handled by subject

**Comment by belgishboy** [comment]
> do we actually need this? server-server connections aren't being handled by subject

Not really but we need to do something since its a valid Command

**Comment by hennneh** [comment]
we're sending an error message
