### ISSUE TITLE
STATS

### ISSUE THREAD

**Issue by belgishboy** [hennneh/ft_irc#69]
/server
Command: STATS
Parameters: [< query > [< server >]]

https://datatracker.ietf.org/doc/html/rfc1459#section-4.3.2

c - returns a list of servers which the server may connect to or allow connections from;

h - returns a list of servers which are either forced to be
               treated as leaves or allowed to act as hubs;
i - returns a list of hosts which the server allows a client
               to connect from;
k - returns a list of banned username/hostname combinations
               for that server;
l - returns a list of the server's connections, showing how long each connection has been established and the traffic
               over that connection in bytes and messages for each direction;
m - returns a list of commands supported by the server and
               the usage count for each if the usage count is non zero;
o - returns a list of hosts from which normal clients may
               become operators;
y - show Y (Class) lines from server's configuration file;
u - returns a string showing how long the server has been up.

**Comment by hennneh** [comment]
we only have one server so we send an error
